openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- description: Generated server url
  url: http://localhost:8080
paths:
  /books:
    get:
      operationId: getBook
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
          description: OK
      tags:
      - books-controller
components:
  schemas:
    Book:
      type: object
      properties:
        author:
          type: string
        title:
          type: string
